export type Continent = "Avrupa" | "Asya" | "Afrika" | "Kuzey Amerika" | "Güney Amerika" | "Okyanusya" | "Antarktika";

export interface Country {
  name: string;
  code: string;   // ISO alpha-3
  code2: string;  // ISO alpha-2 (for flag CDN)
  continent: Continent;
  isSmallIsland?: boolean; // true for small island nations that are hard to find on the map
}

export const countries: Country[] = [
  { name: "Afganistan", code: "AFG", code2: "af", continent: "Asya" },
  { name: "Arnavutluk", code: "ALB", code2: "al", continent: "Avrupa" },
  { name: "Cezayir", code: "DZA", code2: "dz", continent: "Afrika" },
  { name: "Andorra", code: "AND", code2: "ad", continent: "Avrupa" },
  { name: "Angola", code: "AGO", code2: "ao", continent: "Afrika" },
  { name: "Antigua ve Barbuda", code: "ATG", code2: "ag", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Arjantin", code: "ARG", code2: "ar", continent: "Güney Amerika" },
  { name: "Ermenistan", code: "ARM", code2: "am", continent: "Asya" },
  { name: "Avustralya", code: "AUS", code2: "au", continent: "Okyanusya" },
  { name: "Avusturya", code: "AUT", code2: "at", continent: "Avrupa" },
  { name: "Azerbaycan", code: "AZE", code2: "az", continent: "Asya" },
  { name: "Bahamalar", code: "BHS", code2: "bs", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Bahreyn", code: "BHR", code2: "bh", continent: "Asya", isSmallIsland: true },
  { name: "Bangladeş", code: "BGD", code2: "bd", continent: "Asya" },
  { name: "Barbados", code: "BRB", code2: "bb", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Belarus", code: "BLR", code2: "by", continent: "Avrupa" },
  { name: "Belçika", code: "BEL", code2: "be", continent: "Avrupa" },
  { name: "Belize", code: "BLZ", code2: "bz", continent: "Kuzey Amerika" },
  { name: "Benin", code: "BEN", code2: "bj", continent: "Afrika" },
  { name: "Bhutan", code: "BTN", code2: "bt", continent: "Asya" },
  { name: "Bolivya", code: "BOL", code2: "bo", continent: "Güney Amerika" },
  { name: "Bosna Hersek", code: "BIH", code2: "ba", continent: "Avrupa" },
  { name: "Botsvana", code: "BWA", code2: "bw", continent: "Afrika" },
  { name: "Brezilya", code: "BRA", code2: "br", continent: "Güney Amerika" },
  { name: "Brunei", code: "BRN", code2: "bn", continent: "Asya", isSmallIsland: true },
  { name: "Bulgaristan", code: "BGR", code2: "bg", continent: "Avrupa" },
  { name: "Burkina Faso", code: "BFA", code2: "bf", continent: "Afrika" },
  { name: "Burundi", code: "BDI", code2: "bi", continent: "Afrika" },
  { name: "Kamboçya", code: "KHM", code2: "kh", continent: "Asya" },
  { name: "Kamerun", code: "CMR", code2: "cm", continent: "Afrika" },
  { name: "Kanada", code: "CAN", code2: "ca", continent: "Kuzey Amerika" },
  { name: "Cabo Verde", code: "CPV", code2: "cv", continent: "Afrika", isSmallIsland: true },
  { name: "Orta Afrika Cumhuriyeti", code: "CAF", code2: "cf", continent: "Afrika" },
  { name: "Çad", code: "TCD", code2: "td", continent: "Afrika" },
  { name: "Şili", code: "CHL", code2: "cl", continent: "Güney Amerika" },
  { name: "Çin", code: "CHN", code2: "cn", continent: "Asya" },
  { name: "Kolombiya", code: "COL", code2: "co", continent: "Güney Amerika" },
  { name: "Komorlar", code: "COM", code2: "km", continent: "Afrika", isSmallIsland: true },
  { name: "Kongo Cumhuriyeti", code: "COG", code2: "cg", continent: "Afrika" },
  { name: "Kongo Demokratik Cumhuriyeti", code: "COD", code2: "cd", continent: "Afrika" },
  { name: "Kosta Rika", code: "CRI", code2: "cr", continent: "Kuzey Amerika" },
  { name: "Hırvatistan", code: "HRV", code2: "hr", continent: "Avrupa" },
  { name: "Küba", code: "CUB", code2: "cu", continent: "Kuzey Amerika" },
  { name: "Kıbrıs", code: "CYP", code2: "cy", continent: "Avrupa" },
  { name: "Çekya", code: "CZE", code2: "cz", continent: "Avrupa" },
  { name: "Danimarka", code: "DNK", code2: "dk", continent: "Avrupa" },
  { name: "Cibuti", code: "DJI", code2: "dj", continent: "Afrika" },
  { name: "Dominika", code: "DMA", code2: "dm", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Dominik Cumhuriyeti", code: "DOM", code2: "do", continent: "Kuzey Amerika" },
  { name: "Ekvador", code: "ECU", code2: "ec", continent: "Güney Amerika" },
  { name: "Mısır", code: "EGY", code2: "eg", continent: "Afrika" },
  { name: "El Salvador", code: "SLV", code2: "sv", continent: "Kuzey Amerika" },
  { name: "Ekvator Ginesi", code: "GNQ", code2: "gq", continent: "Afrika" },
  { name: "Eritre", code: "ERI", code2: "er", continent: "Afrika" },
  { name: "Estonya", code: "EST", code2: "ee", continent: "Avrupa" },
  { name: "Esvatini", code: "SWZ", code2: "sz", continent: "Afrika" },
  { name: "Etiyopya", code: "ETH", code2: "et", continent: "Afrika" },
  { name: "Fiji", code: "FJI", code2: "fj", continent: "Okyanusya", isSmallIsland: true },
  { name: "Finlandiya", code: "FIN", code2: "fi", continent: "Avrupa" },
  { name: "Fransa", code: "FRA", code2: "fr", continent: "Avrupa" },
  { name: "Gabon", code: "GAB", code2: "ga", continent: "Afrika" },
  { name: "Gambiya", code: "GMB", code2: "gm", continent: "Afrika" },
  { name: "Gürcistan", code: "GEO", code2: "ge", continent: "Asya" },
  { name: "Almanya", code: "DEU", code2: "de", continent: "Avrupa" },
  { name: "Gana", code: "GHA", code2: "gh", continent: "Afrika" },
  { name: "Yunanistan", code: "GRC", code2: "gr", continent: "Avrupa" },
  { name: "Grenada", code: "GRD", code2: "gd", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Guatemala", code: "GTM", code2: "gt", continent: "Kuzey Amerika" },
  { name: "Gine", code: "GIN", code2: "gn", continent: "Afrika" },
  { name: "Gine-Bissau", code: "GNB", code2: "gw", continent: "Afrika" },
  { name: "Guyana", code: "GUY", code2: "gy", continent: "Güney Amerika" },
  { name: "Haiti", code: "HTI", code2: "ht", continent: "Kuzey Amerika" },
  { name: "Honduras", code: "HND", code2: "hn", continent: "Kuzey Amerika" },
  { name: "Macaristan", code: "HUN", code2: "hu", continent: "Avrupa" },
  { name: "İzlanda", code: "ISL", code2: "is", continent: "Avrupa" },
  { name: "Hindistan", code: "IND", code2: "in", continent: "Asya" },
  { name: "Endonezya", code: "IDN", code2: "id", continent: "Asya" },
  { name: "İran", code: "IRN", code2: "ir", continent: "Asya" },
  { name: "Irak", code: "IRQ", code2: "iq", continent: "Asya" },
  { name: "İrlanda", code: "IRL", code2: "ie", continent: "Avrupa" },
  { name: "İsrail", code: "ISR", code2: "il", continent: "Asya" },
  { name: "İtalya", code: "ITA", code2: "it", continent: "Avrupa" },
  { name: "Fildişi Sahili", code: "CIV", code2: "ci", continent: "Afrika" },
  { name: "Jamaika", code: "JAM", code2: "jm", continent: "Kuzey Amerika" },
  { name: "Japonya", code: "JPN", code2: "jp", continent: "Asya" },
  { name: "Ürdün", code: "JOR", code2: "jo", continent: "Asya" },
  { name: "Kazakistan", code: "KAZ", code2: "kz", continent: "Asya" },
  { name: "Kenya", code: "KEN", code2: "ke", continent: "Afrika" },
  { name: "Kiribati", code: "KIR", code2: "ki", continent: "Okyanusya", isSmallIsland: true },
  { name: "Kuzey Kore", code: "PRK", code2: "kp", continent: "Asya" },
  { name: "Güney Kore", code: "KOR", code2: "kr", continent: "Asya" },
  { name: "Kosova", code: "XKX", code2: "xk", continent: "Avrupa" },
  { name: "Kuveyt", code: "KWT", code2: "kw", continent: "Asya" },
  { name: "Kırgızistan", code: "KGZ", code2: "kg", continent: "Asya" },
  { name: "Laos", code: "LAO", code2: "la", continent: "Asya" },
  { name: "Letonya", code: "LVA", code2: "lv", continent: "Avrupa" },
  { name: "Lübnan", code: "LBN", code2: "lb", continent: "Asya" },
  { name: "Lesotho", code: "LSO", code2: "ls", continent: "Afrika" },
  { name: "Liberya", code: "LBR", code2: "lr", continent: "Afrika" },
  { name: "Libya", code: "LBY", code2: "ly", continent: "Afrika" },
  { name: "Lihtenştayn", code: "LIE", code2: "li", continent: "Avrupa" },
  { name: "Litvanya", code: "LTU", code2: "lt", continent: "Avrupa" },
  { name: "Lüksemburg", code: "LUX", code2: "lu", continent: "Avrupa" },
  { name: "Kuzey Makedonya", code: "MKD", code2: "mk", continent: "Avrupa" },
  { name: "Madagaskar", code: "MDG", code2: "mg", continent: "Afrika" },
  { name: "Malavi", code: "MWI", code2: "mw", continent: "Afrika" },
  { name: "Malezya", code: "MYS", code2: "my", continent: "Asya" },
  { name: "Maldivler", code: "MDV", code2: "mv", continent: "Asya", isSmallIsland: true },
  { name: "Mali", code: "MLI", code2: "ml", continent: "Afrika" },
  { name: "Malta", code: "MLT", code2: "mt", continent: "Avrupa", isSmallIsland: true },
  { name: "Marshall Adaları", code: "MHL", code2: "mh", continent: "Okyanusya", isSmallIsland: true },
  { name: "Moritanya", code: "MRT", code2: "mr", continent: "Afrika" },
  { name: "Mauritius", code: "MUS", code2: "mu", continent: "Afrika", isSmallIsland: true },
  { name: "Meksika", code: "MEX", code2: "mx", continent: "Kuzey Amerika" },
  { name: "Mikronezya", code: "FSM", code2: "fm", continent: "Okyanusya", isSmallIsland: true },
  { name: "Moldova", code: "MDA", code2: "md", continent: "Avrupa" },
  { name: "Monako", code: "MCO", code2: "mc", continent: "Avrupa" },
  { name: "Moğolistan", code: "MNG", code2: "mn", continent: "Asya" },
  { name: "Karadağ", code: "MNE", code2: "me", continent: "Avrupa" },
  { name: "Fas", code: "MAR", code2: "ma", continent: "Afrika" },
  { name: "Mozambik", code: "MOZ", code2: "mz", continent: "Afrika" },
  { name: "Myanmar", code: "MMR", code2: "mm", continent: "Asya" },
  { name: "Namibya", code: "NAM", code2: "na", continent: "Afrika" },
  { name: "Nauru", code: "NRU", code2: "nr", continent: "Okyanusya", isSmallIsland: true },
  { name: "Nepal", code: "NPL", code2: "np", continent: "Asya" },
  { name: "Hollanda", code: "NLD", code2: "nl", continent: "Avrupa" },
  { name: "Yeni Zelanda", code: "NZL", code2: "nz", continent: "Okyanusya" },
  { name: "Nikaragua", code: "NIC", code2: "ni", continent: "Kuzey Amerika" },
  { name: "Nijer", code: "NER", code2: "ne", continent: "Afrika" },
  { name: "Nijerya", code: "NGA", code2: "ng", continent: "Afrika" },
  { name: "Norveç", code: "NOR", code2: "no", continent: "Avrupa" },
  { name: "Umman", code: "OMN", code2: "om", continent: "Asya" },
  { name: "Pakistan", code: "PAK", code2: "pk", continent: "Asya" },
  { name: "Palau", code: "PLW", code2: "pw", continent: "Okyanusya", isSmallIsland: true },
  { name: "Filistin", code: "PSE", code2: "ps", continent: "Asya" },
  { name: "Panama", code: "PAN", code2: "pa", continent: "Kuzey Amerika" },
  { name: "Papua Yeni Gine", code: "PNG", code2: "pg", continent: "Okyanusya" },
  { name: "Paraguay", code: "PRY", code2: "py", continent: "Güney Amerika" },
  { name: "Peru", code: "PER", code2: "pe", continent: "Güney Amerika" },
  { name: "Filipinler", code: "PHL", code2: "ph", continent: "Asya" },
  { name: "Polonya", code: "POL", code2: "pl", continent: "Avrupa" },
  { name: "Portekiz", code: "PRT", code2: "pt", continent: "Avrupa" },
  { name: "Katar", code: "QAT", code2: "qa", continent: "Asya" },
  { name: "Romanya", code: "ROU", code2: "ro", continent: "Avrupa" },
  { name: "Rusya", code: "RUS", code2: "ru", continent: "Avrupa" },
  { name: "Ruanda", code: "RWA", code2: "rw", continent: "Afrika" },
  { name: "Saint Kitts ve Nevis", code: "KNA", code2: "kn", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Saint Lucia", code: "LCA", code2: "lc", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Saint Vincent ve Grenadinler", code: "VCT", code2: "vc", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Samoa", code: "WSM", code2: "ws", continent: "Okyanusya", isSmallIsland: true },
  { name: "San Marino", code: "SMR", code2: "sm", continent: "Avrupa" },
  { name: "São Tomé ve Príncipe", code: "STP", code2: "st", continent: "Afrika", isSmallIsland: true },
  { name: "Suudi Arabistan", code: "SAU", code2: "sa", continent: "Asya" },
  { name: "Senegal", code: "SEN", code2: "sn", continent: "Afrika" },
  { name: "Sırbistan", code: "SRB", code2: "rs", continent: "Avrupa" },
  { name: "Seyşeller", code: "SYC", code2: "sc", continent: "Afrika", isSmallIsland: true },
  { name: "Sierra Leone", code: "SLE", code2: "sl", continent: "Afrika" },
  { name: "Singapur", code: "SGP", code2: "sg", continent: "Asya", isSmallIsland: true },
  { name: "Slovakya", code: "SVK", code2: "sk", continent: "Avrupa" },
  { name: "Slovenya", code: "SVN", code2: "si", continent: "Avrupa" },
  { name: "Solomon Adaları", code: "SLB", code2: "sb", continent: "Okyanusya", isSmallIsland: true },
  { name: "Somali", code: "SOM", code2: "so", continent: "Afrika" },
  { name: "Güney Afrika", code: "ZAF", code2: "za", continent: "Afrika" },
  { name: "Güney Sudan", code: "SSD", code2: "ss", continent: "Afrika" },
  { name: "İspanya", code: "ESP", code2: "es", continent: "Avrupa" },
  { name: "Sri Lanka", code: "LKA", code2: "lk", continent: "Asya" },
  { name: "Sudan", code: "SDN", code2: "sd", continent: "Afrika" },
  { name: "Surinam", code: "SUR", code2: "sr", continent: "Güney Amerika" },
  { name: "İsveç", code: "SWE", code2: "se", continent: "Avrupa" },
  { name: "İsviçre", code: "CHE", code2: "ch", continent: "Avrupa" },
  { name: "Suriye", code: "SYR", code2: "sy", continent: "Asya" },
  { name: "Tayvan", code: "TWN", code2: "tw", continent: "Asya" },
  { name: "Tacikistan", code: "TJK", code2: "tj", continent: "Asya" },
  { name: "Tanzanya", code: "TZA", code2: "tz", continent: "Afrika" },
  { name: "Tayland", code: "THA", code2: "th", continent: "Asya" },
  { name: "Doğu Timor", code: "TLS", code2: "tl", continent: "Asya" },
  { name: "Togo", code: "TGO", code2: "tg", continent: "Afrika" },
  { name: "Tonga", code: "TON", code2: "to", continent: "Okyanusya", isSmallIsland: true },
  { name: "Trinidad ve Tobago", code: "TTO", code2: "tt", continent: "Kuzey Amerika", isSmallIsland: true },
  { name: "Tunus", code: "TUN", code2: "tn", continent: "Afrika" },
  { name: "Türkiye", code: "TUR", code2: "tr", continent: "Avrupa" },
  { name: "Türkmenistan", code: "TKM", code2: "tm", continent: "Asya" },
  { name: "Uganda", code: "UGA", code2: "ug", continent: "Afrika" },
  { name: "Ukrayna", code: "UKR", code2: "ua", continent: "Avrupa" },
  { name: "Birleşik Arap Emirlikleri", code: "ARE", code2: "ae", continent: "Asya" },
  { name: "Birleşik Krallık", code: "GBR", code2: "gb", continent: "Avrupa" },
  { name: "Amerika Birleşik Devletleri", code: "USA", code2: "us", continent: "Kuzey Amerika" },
  { name: "Uruguay", code: "URY", code2: "uy", continent: "Güney Amerika" },
  { name: "Özbekistan", code: "UZB", code2: "uz", continent: "Asya" },
  { name: "Vanuatu", code: "VUT", code2: "vu", continent: "Okyanusya", isSmallIsland: true },
  { name: "Vatikan", code: "VAT", code2: "va", continent: "Avrupa" },
  { name: "Venezuela", code: "VEN", code2: "ve", continent: "Güney Amerika" },
  { name: "Vietnam", code: "VNM", code2: "vn", continent: "Asya" },
  { name: "Yemen", code: "YEM", code2: "ye", continent: "Asya" },
  { name: "Zambiya", code: "ZMB", code2: "zm", continent: "Afrika" },
  { name: "Zimbabve", code: "ZWE", code2: "zw", continent: "Afrika" },
  { name: "Batı Sahra", code: "ESH", code2: "eh", continent: "Afrika" },
  { name: "Grönland", code: "GRL", code2: "gl", continent: "Kuzey Amerika" },
  { name: "Porto Riko", code: "PRI", code2: "pr", continent: "Kuzey Amerika" },
  { name: "Falkland Adaları", code: "FLK", code2: "fk", continent: "Güney Amerika" },
  { name: "Antarktika", code: "ATA", code2: "aq", continent: "Antarktika" },
  { name: "Yeni Kaledonya", code: "NCL", code2: "nc", continent: "Okyanusya" },
];

// Shuffle an array (Fisher-Yates)
export function shuffleArray<T>(arr: T[]): T[] {
  const result = [...arr];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

// Get filtered countries based on settings
export function getFilteredCountries(includeSmallIslands: boolean): Country[] {
  if (includeSmallIslands) return countries;
  return countries.filter(c => !c.isSmallIsland);
}
