export type Continent = "europe" | "asia" | "africa" | "northAmerica" | "southAmerica" | "oceania" | "antarctica";

export const CONTINENTS: Continent[] = ["europe", "asia", "africa", "northAmerica", "southAmerica", "oceania", "antarctica"];

export interface Country {
  name: string;   // Turkish
  en: string;     // English
  code: string;   // ISO alpha-3
  code2: string;  // ISO alpha-2 (flag file name)
  continent: Continent;
  capital?: string;   // Turkish; Antarctica has none
  capitalEn?: string; // only when it differs from the Turkish name
  isSmallIsland?: boolean; // true for small island nations that are hard to find on the map
}

export const countries: Country[] = [
  { name: "Afganistan", en: "Afghanistan", code: "AFG", code2: "af", continent: "asia", capital: "Kabil", capitalEn: "Kabul" },
  { name: "Arnavutluk", en: "Albania", code: "ALB", code2: "al", continent: "europe", capital: "Tiran", capitalEn: "Tirana" },
  { name: "Cezayir", en: "Algeria", code: "DZA", code2: "dz", continent: "africa", capital: "Cezayir", capitalEn: "Algiers" },
  { name: "Andorra", en: "Andorra", code: "AND", code2: "ad", continent: "europe", capital: "Andorra la Vella" },
  { name: "Angola", en: "Angola", code: "AGO", code2: "ao", continent: "africa", capital: "Luanda" },
  { name: "Antigua ve Barbuda", en: "Antigua and Barbuda", code: "ATG", code2: "ag", continent: "northAmerica", capital: "Saint John's", isSmallIsland: true },
  { name: "Arjantin", en: "Argentina", code: "ARG", code2: "ar", continent: "southAmerica", capital: "Buenos Aires" },
  { name: "Ermenistan", en: "Armenia", code: "ARM", code2: "am", continent: "asia", capital: "Erivan", capitalEn: "Yerevan" },
  { name: "Avustralya", en: "Australia", code: "AUS", code2: "au", continent: "oceania", capital: "Kanberra", capitalEn: "Canberra" },
  { name: "Avusturya", en: "Austria", code: "AUT", code2: "at", continent: "europe", capital: "Viyana", capitalEn: "Vienna" },
  { name: "Azerbaycan", en: "Azerbaijan", code: "AZE", code2: "az", continent: "asia", capital: "Bakü", capitalEn: "Baku" },
  { name: "Bahamalar", en: "Bahamas", code: "BHS", code2: "bs", continent: "northAmerica", capital: "Nassau", isSmallIsland: true },
  { name: "Bahreyn", en: "Bahrain", code: "BHR", code2: "bh", continent: "asia", capital: "Manama", isSmallIsland: true },
  { name: "Bangladeş", en: "Bangladesh", code: "BGD", code2: "bd", continent: "asia", capital: "Dakka", capitalEn: "Dhaka" },
  { name: "Barbados", en: "Barbados", code: "BRB", code2: "bb", continent: "northAmerica", capital: "Bridgetown", isSmallIsland: true },
  { name: "Belarus", en: "Belarus", code: "BLR", code2: "by", continent: "europe", capital: "Minsk" },
  { name: "Belçika", en: "Belgium", code: "BEL", code2: "be", continent: "europe", capital: "Brüksel", capitalEn: "Brussels" },
  { name: "Belize", en: "Belize", code: "BLZ", code2: "bz", continent: "northAmerica", capital: "Belmopan" },
  { name: "Benin", en: "Benin", code: "BEN", code2: "bj", continent: "africa", capital: "Porto-Novo" },
  { name: "Bhutan", en: "Bhutan", code: "BTN", code2: "bt", continent: "asia", capital: "Thimphu" },
  { name: "Bolivya", en: "Bolivia", code: "BOL", code2: "bo", continent: "southAmerica", capital: "Sucre" },
  { name: "Bosna Hersek", en: "Bosnia and Herzegovina", code: "BIH", code2: "ba", continent: "europe", capital: "Saraybosna", capitalEn: "Sarajevo" },
  { name: "Botsvana", en: "Botswana", code: "BWA", code2: "bw", continent: "africa", capital: "Gaborone" },
  { name: "Brezilya", en: "Brazil", code: "BRA", code2: "br", continent: "southAmerica", capital: "Brasília" },
  { name: "Brunei", en: "Brunei", code: "BRN", code2: "bn", continent: "asia", capital: "Bandar Seri Begawan", isSmallIsland: true },
  { name: "Bulgaristan", en: "Bulgaria", code: "BGR", code2: "bg", continent: "europe", capital: "Sofya", capitalEn: "Sofia" },
  { name: "Burkina Faso", en: "Burkina Faso", code: "BFA", code2: "bf", continent: "africa", capital: "Vagadugu", capitalEn: "Ouagadougou" },
  { name: "Burundi", en: "Burundi", code: "BDI", code2: "bi", continent: "africa", capital: "Gitega" },
  { name: "Kamboçya", en: "Cambodia", code: "KHM", code2: "kh", continent: "asia", capital: "Phnom Penh" },
  { name: "Kamerun", en: "Cameroon", code: "CMR", code2: "cm", continent: "africa", capital: "Yaoundé" },
  { name: "Kanada", en: "Canada", code: "CAN", code2: "ca", continent: "northAmerica", capital: "Ottava", capitalEn: "Ottawa" },
  { name: "Cabo Verde", en: "Cape Verde", code: "CPV", code2: "cv", continent: "africa", capital: "Praia", isSmallIsland: true },
  { name: "Orta Afrika Cumhuriyeti", en: "Central African Republic", code: "CAF", code2: "cf", continent: "africa", capital: "Bangui" },
  { name: "Çad", en: "Chad", code: "TCD", code2: "td", continent: "africa", capital: "Ncamena", capitalEn: "N'Djamena" },
  { name: "Şili", en: "Chile", code: "CHL", code2: "cl", continent: "southAmerica", capital: "Santiago" },
  { name: "Çin", en: "China", code: "CHN", code2: "cn", continent: "asia", capital: "Pekin", capitalEn: "Beijing" },
  { name: "Kolombiya", en: "Colombia", code: "COL", code2: "co", continent: "southAmerica", capital: "Bogota", capitalEn: "Bogotá" },
  { name: "Komorlar", en: "Comoros", code: "COM", code2: "km", continent: "africa", capital: "Moroni", isSmallIsland: true },
  { name: "Kongo Cumhuriyeti", en: "Republic of the Congo", code: "COG", code2: "cg", continent: "africa", capital: "Brazzaville" },
  { name: "Kongo Demokratik Cumhuriyeti", en: "DR Congo", code: "COD", code2: "cd", continent: "africa", capital: "Kinşasa", capitalEn: "Kinshasa" },
  { name: "Kosta Rika", en: "Costa Rica", code: "CRI", code2: "cr", continent: "northAmerica", capital: "San José" },
  { name: "Hırvatistan", en: "Croatia", code: "HRV", code2: "hr", continent: "europe", capital: "Zagreb" },
  { name: "Küba", en: "Cuba", code: "CUB", code2: "cu", continent: "northAmerica", capital: "Havana" },
  { name: "Kıbrıs", en: "Cyprus", code: "CYP", code2: "cy", continent: "europe", capital: "Lefkoşa", capitalEn: "Nicosia" },
  { name: "Çekya", en: "Czechia", code: "CZE", code2: "cz", continent: "europe", capital: "Prag", capitalEn: "Prague" },
  { name: "Danimarka", en: "Denmark", code: "DNK", code2: "dk", continent: "europe", capital: "Kopenhag", capitalEn: "Copenhagen" },
  { name: "Cibuti", en: "Djibouti", code: "DJI", code2: "dj", continent: "africa", capital: "Cibuti", capitalEn: "Djibouti" },
  { name: "Dominika", en: "Dominica", code: "DMA", code2: "dm", continent: "northAmerica", capital: "Roseau", isSmallIsland: true },
  { name: "Dominik Cumhuriyeti", en: "Dominican Republic", code: "DOM", code2: "do", continent: "northAmerica", capital: "Santo Domingo" },
  { name: "Ekvador", en: "Ecuador", code: "ECU", code2: "ec", continent: "southAmerica", capital: "Quito" },
  { name: "Mısır", en: "Egypt", code: "EGY", code2: "eg", continent: "africa", capital: "Kahire", capitalEn: "Cairo" },
  { name: "El Salvador", en: "El Salvador", code: "SLV", code2: "sv", continent: "northAmerica", capital: "San Salvador" },
  { name: "Ekvator Ginesi", en: "Equatorial Guinea", code: "GNQ", code2: "gq", continent: "africa", capital: "Malabo" },
  { name: "Eritre", en: "Eritrea", code: "ERI", code2: "er", continent: "africa", capital: "Asmara" },
  { name: "Estonya", en: "Estonia", code: "EST", code2: "ee", continent: "europe", capital: "Tallinn" },
  { name: "Esvatini", en: "Eswatini", code: "SWZ", code2: "sz", continent: "africa", capital: "Mbabane" },
  { name: "Etiyopya", en: "Ethiopia", code: "ETH", code2: "et", continent: "africa", capital: "Addis Ababa" },
  { name: "Fiji", en: "Fiji", code: "FJI", code2: "fj", continent: "oceania", capital: "Suva", isSmallIsland: true },
  { name: "Finlandiya", en: "Finland", code: "FIN", code2: "fi", continent: "europe", capital: "Helsinki" },
  { name: "Fransa", en: "France", code: "FRA", code2: "fr", continent: "europe", capital: "Paris" },
  { name: "Gabon", en: "Gabon", code: "GAB", code2: "ga", continent: "africa", capital: "Libreville" },
  { name: "Gambiya", en: "Gambia", code: "GMB", code2: "gm", continent: "africa", capital: "Banjul" },
  { name: "Gürcistan", en: "Georgia", code: "GEO", code2: "ge", continent: "asia", capital: "Tiflis", capitalEn: "Tbilisi" },
  { name: "Almanya", en: "Germany", code: "DEU", code2: "de", continent: "europe", capital: "Berlin" },
  { name: "Gana", en: "Ghana", code: "GHA", code2: "gh", continent: "africa", capital: "Akra", capitalEn: "Accra" },
  { name: "Yunanistan", en: "Greece", code: "GRC", code2: "gr", continent: "europe", capital: "Atina", capitalEn: "Athens" },
  { name: "Grenada", en: "Grenada", code: "GRD", code2: "gd", continent: "northAmerica", capital: "Saint George's", isSmallIsland: true },
  { name: "Guatemala", en: "Guatemala", code: "GTM", code2: "gt", continent: "northAmerica", capital: "Guatemala", capitalEn: "Guatemala City" },
  { name: "Gine", en: "Guinea", code: "GIN", code2: "gn", continent: "africa", capital: "Konakri", capitalEn: "Conakry" },
  { name: "Gine-Bissau", en: "Guinea-Bissau", code: "GNB", code2: "gw", continent: "africa", capital: "Bissau" },
  { name: "Guyana", en: "Guyana", code: "GUY", code2: "gy", continent: "southAmerica", capital: "Georgetown" },
  { name: "Haiti", en: "Haiti", code: "HTI", code2: "ht", continent: "northAmerica", capital: "Port-au-Prince" },
  { name: "Honduras", en: "Honduras", code: "HND", code2: "hn", continent: "northAmerica", capital: "Tegucigalpa" },
  { name: "Macaristan", en: "Hungary", code: "HUN", code2: "hu", continent: "europe", capital: "Budapeşte", capitalEn: "Budapest" },
  { name: "İzlanda", en: "Iceland", code: "ISL", code2: "is", continent: "europe", capital: "Reykjavik", capitalEn: "Reykjavík" },
  { name: "Hindistan", en: "India", code: "IND", code2: "in", continent: "asia", capital: "Yeni Delhi", capitalEn: "New Delhi" },
  { name: "Endonezya", en: "Indonesia", code: "IDN", code2: "id", continent: "asia", capital: "Cakarta", capitalEn: "Jakarta" },
  { name: "İran", en: "Iran", code: "IRN", code2: "ir", continent: "asia", capital: "Tahran", capitalEn: "Tehran" },
  { name: "Irak", en: "Iraq", code: "IRQ", code2: "iq", continent: "asia", capital: "Bağdat", capitalEn: "Baghdad" },
  { name: "İrlanda", en: "Ireland", code: "IRL", code2: "ie", continent: "europe", capital: "Dublin" },
  { name: "İsrail", en: "Israel", code: "ISR", code2: "il", continent: "asia", capital: "Kudüs", capitalEn: "Jerusalem" },
  { name: "İtalya", en: "Italy", code: "ITA", code2: "it", continent: "europe", capital: "Roma", capitalEn: "Rome" },
  { name: "Fildişi Sahili", en: "Ivory Coast", code: "CIV", code2: "ci", continent: "africa", capital: "Yamusukro", capitalEn: "Yamoussoukro" },
  { name: "Jamaika", en: "Jamaica", code: "JAM", code2: "jm", continent: "northAmerica", capital: "Kingston" },
  { name: "Japonya", en: "Japan", code: "JPN", code2: "jp", continent: "asia", capital: "Tokyo" },
  { name: "Ürdün", en: "Jordan", code: "JOR", code2: "jo", continent: "asia", capital: "Amman" },
  { name: "Kazakistan", en: "Kazakhstan", code: "KAZ", code2: "kz", continent: "asia", capital: "Astana" },
  { name: "Kenya", en: "Kenya", code: "KEN", code2: "ke", continent: "africa", capital: "Nairobi" },
  { name: "Kiribati", en: "Kiribati", code: "KIR", code2: "ki", continent: "oceania", capital: "Tarawa", isSmallIsland: true },
  { name: "Kuzey Kore", en: "North Korea", code: "PRK", code2: "kp", continent: "asia", capital: "Pyongyang" },
  { name: "Güney Kore", en: "South Korea", code: "KOR", code2: "kr", continent: "asia", capital: "Seul", capitalEn: "Seoul" },
  { name: "Kosova", en: "Kosovo", code: "XKX", code2: "xk", continent: "europe", capital: "Priştine", capitalEn: "Pristina" },
  { name: "Kuveyt", en: "Kuwait", code: "KWT", code2: "kw", continent: "asia", capital: "Kuveyt", capitalEn: "Kuwait City" },
  { name: "Kırgızistan", en: "Kyrgyzstan", code: "KGZ", code2: "kg", continent: "asia", capital: "Bişkek", capitalEn: "Bishkek" },
  { name: "Laos", en: "Laos", code: "LAO", code2: "la", continent: "asia", capital: "Vientiane" },
  { name: "Letonya", en: "Latvia", code: "LVA", code2: "lv", continent: "europe", capital: "Riga" },
  { name: "Lübnan", en: "Lebanon", code: "LBN", code2: "lb", continent: "asia", capital: "Beyrut", capitalEn: "Beirut" },
  { name: "Lesotho", en: "Lesotho", code: "LSO", code2: "ls", continent: "africa", capital: "Maseru" },
  { name: "Liberya", en: "Liberia", code: "LBR", code2: "lr", continent: "africa", capital: "Monrovia" },
  { name: "Libya", en: "Libya", code: "LBY", code2: "ly", continent: "africa", capital: "Trablus", capitalEn: "Tripoli" },
  { name: "Lihtenştayn", en: "Liechtenstein", code: "LIE", code2: "li", continent: "europe", capital: "Vaduz" },
  { name: "Litvanya", en: "Lithuania", code: "LTU", code2: "lt", continent: "europe", capital: "Vilnius" },
  { name: "Lüksemburg", en: "Luxembourg", code: "LUX", code2: "lu", continent: "europe", capital: "Lüksemburg", capitalEn: "Luxembourg" },
  { name: "Kuzey Makedonya", en: "North Macedonia", code: "MKD", code2: "mk", continent: "europe", capital: "Üsküp", capitalEn: "Skopje" },
  { name: "Madagaskar", en: "Madagascar", code: "MDG", code2: "mg", continent: "africa", capital: "Antananarivo" },
  { name: "Malavi", en: "Malawi", code: "MWI", code2: "mw", continent: "africa", capital: "Lilongwe" },
  { name: "Malezya", en: "Malaysia", code: "MYS", code2: "my", continent: "asia", capital: "Kuala Lumpur" },
  { name: "Maldivler", en: "Maldives", code: "MDV", code2: "mv", continent: "asia", capital: "Male", capitalEn: "Malé", isSmallIsland: true },
  { name: "Mali", en: "Mali", code: "MLI", code2: "ml", continent: "africa", capital: "Bamako" },
  { name: "Malta", en: "Malta", code: "MLT", code2: "mt", continent: "europe", capital: "Valletta", isSmallIsland: true },
  { name: "Marshall Adaları", en: "Marshall Islands", code: "MHL", code2: "mh", continent: "oceania", capital: "Majuro", isSmallIsland: true },
  { name: "Moritanya", en: "Mauritania", code: "MRT", code2: "mr", continent: "africa", capital: "Nouakchott" },
  { name: "Mauritius", en: "Mauritius", code: "MUS", code2: "mu", continent: "africa", capital: "Port Louis", isSmallIsland: true },
  { name: "Meksika", en: "Mexico", code: "MEX", code2: "mx", continent: "northAmerica", capital: "Meksiko", capitalEn: "Mexico City" },
  { name: "Mikronezya", en: "Micronesia", code: "FSM", code2: "fm", continent: "oceania", capital: "Palikir", isSmallIsland: true },
  { name: "Moldova", en: "Moldova", code: "MDA", code2: "md", continent: "europe", capital: "Kişinev", capitalEn: "Chișinău" },
  { name: "Monako", en: "Monaco", code: "MCO", code2: "mc", continent: "europe", capital: "Monako", capitalEn: "Monaco" },
  { name: "Moğolistan", en: "Mongolia", code: "MNG", code2: "mn", continent: "asia", capital: "Ulan Batur", capitalEn: "Ulaanbaatar" },
  { name: "Karadağ", en: "Montenegro", code: "MNE", code2: "me", continent: "europe", capital: "Podgorica" },
  { name: "Fas", en: "Morocco", code: "MAR", code2: "ma", continent: "africa", capital: "Rabat" },
  { name: "Mozambik", en: "Mozambique", code: "MOZ", code2: "mz", continent: "africa", capital: "Maputo" },
  { name: "Myanmar", en: "Myanmar", code: "MMR", code2: "mm", continent: "asia", capital: "Naypyidaw" },
  { name: "Namibya", en: "Namibia", code: "NAM", code2: "na", continent: "africa", capital: "Windhoek" },
  { name: "Nauru", en: "Nauru", code: "NRU", code2: "nr", continent: "oceania", capital: "Yaren", isSmallIsland: true },
  { name: "Nepal", en: "Nepal", code: "NPL", code2: "np", continent: "asia", capital: "Katmandu", capitalEn: "Kathmandu" },
  { name: "Hollanda", en: "Netherlands", code: "NLD", code2: "nl", continent: "europe", capital: "Amsterdam" },
  { name: "Yeni Zelanda", en: "New Zealand", code: "NZL", code2: "nz", continent: "oceania", capital: "Wellington" },
  { name: "Nikaragua", en: "Nicaragua", code: "NIC", code2: "ni", continent: "northAmerica", capital: "Managua" },
  { name: "Nijer", en: "Niger", code: "NER", code2: "ne", continent: "africa", capital: "Niamey" },
  { name: "Nijerya", en: "Nigeria", code: "NGA", code2: "ng", continent: "africa", capital: "Abuja" },
  { name: "Norveç", en: "Norway", code: "NOR", code2: "no", continent: "europe", capital: "Oslo" },
  { name: "Umman", en: "Oman", code: "OMN", code2: "om", continent: "asia", capital: "Maskat", capitalEn: "Muscat" },
  { name: "Pakistan", en: "Pakistan", code: "PAK", code2: "pk", continent: "asia", capital: "İslamabad", capitalEn: "Islamabad" },
  { name: "Palau", en: "Palau", code: "PLW", code2: "pw", continent: "oceania", capital: "Ngerulmud", isSmallIsland: true },
  { name: "Filistin", en: "Palestine", code: "PSE", code2: "ps", continent: "asia", capital: "Ramallah" },
  { name: "Panama", en: "Panama", code: "PAN", code2: "pa", continent: "northAmerica", capital: "Panama", capitalEn: "Panama City" },
  { name: "Papua Yeni Gine", en: "Papua New Guinea", code: "PNG", code2: "pg", continent: "oceania", capital: "Port Moresby" },
  { name: "Paraguay", en: "Paraguay", code: "PRY", code2: "py", continent: "southAmerica", capital: "Asunción" },
  { name: "Peru", en: "Peru", code: "PER", code2: "pe", continent: "southAmerica", capital: "Lima" },
  { name: "Filipinler", en: "Philippines", code: "PHL", code2: "ph", continent: "asia", capital: "Manila" },
  { name: "Polonya", en: "Poland", code: "POL", code2: "pl", continent: "europe", capital: "Varşova", capitalEn: "Warsaw" },
  { name: "Portekiz", en: "Portugal", code: "PRT", code2: "pt", continent: "europe", capital: "Lizbon", capitalEn: "Lisbon" },
  { name: "Katar", en: "Qatar", code: "QAT", code2: "qa", continent: "asia", capital: "Doha" },
  { name: "Romanya", en: "Romania", code: "ROU", code2: "ro", continent: "europe", capital: "Bükreş", capitalEn: "Bucharest" },
  { name: "Rusya", en: "Russia", code: "RUS", code2: "ru", continent: "europe", capital: "Moskova", capitalEn: "Moscow" },
  { name: "Ruanda", en: "Rwanda", code: "RWA", code2: "rw", continent: "africa", capital: "Kigali" },
  { name: "Saint Kitts ve Nevis", en: "Saint Kitts and Nevis", code: "KNA", code2: "kn", continent: "northAmerica", capital: "Basseterre", isSmallIsland: true },
  { name: "Saint Lucia", en: "Saint Lucia", code: "LCA", code2: "lc", continent: "northAmerica", capital: "Castries", isSmallIsland: true },
  { name: "Saint Vincent ve Grenadinler", en: "Saint Vincent and Grenadines", code: "VCT", code2: "vc", continent: "northAmerica", capital: "Kingstown", isSmallIsland: true },
  { name: "Samoa", en: "Samoa", code: "WSM", code2: "ws", continent: "oceania", capital: "Apia", isSmallIsland: true },
  { name: "San Marino", en: "San Marino", code: "SMR", code2: "sm", continent: "europe", capital: "San Marino" },
  { name: "São Tomé ve Príncipe", en: "São Tomé and Príncipe", code: "STP", code2: "st", continent: "africa", capital: "São Tomé", isSmallIsland: true },
  { name: "Suudi Arabistan", en: "Saudi Arabia", code: "SAU", code2: "sa", continent: "asia", capital: "Riyad", capitalEn: "Riyadh" },
  { name: "Senegal", en: "Senegal", code: "SEN", code2: "sn", continent: "africa", capital: "Dakar" },
  { name: "Sırbistan", en: "Serbia", code: "SRB", code2: "rs", continent: "europe", capital: "Belgrad", capitalEn: "Belgrade" },
  { name: "Seyşeller", en: "Seychelles", code: "SYC", code2: "sc", continent: "africa", capital: "Victoria", isSmallIsland: true },
  { name: "Sierra Leone", en: "Sierra Leone", code: "SLE", code2: "sl", continent: "africa", capital: "Freetown" },
  { name: "Singapur", en: "Singapore", code: "SGP", code2: "sg", continent: "asia", capital: "Singapur", capitalEn: "Singapore", isSmallIsland: true },
  { name: "Slovakya", en: "Slovakia", code: "SVK", code2: "sk", continent: "europe", capital: "Bratislava" },
  { name: "Slovenya", en: "Slovenia", code: "SVN", code2: "si", continent: "europe", capital: "Ljubljana" },
  { name: "Solomon Adaları", en: "Solomon Islands", code: "SLB", code2: "sb", continent: "oceania", capital: "Honiara", isSmallIsland: true },
  { name: "Somali", en: "Somalia", code: "SOM", code2: "so", continent: "africa", capital: "Mogadişu", capitalEn: "Mogadishu" },
  { name: "Güney Afrika", en: "South Africa", code: "ZAF", code2: "za", continent: "africa", capital: "Pretoria" },
  { name: "Güney Sudan", en: "South Sudan", code: "SSD", code2: "ss", continent: "africa", capital: "Juba" },
  { name: "İspanya", en: "Spain", code: "ESP", code2: "es", continent: "europe", capital: "Madrid" },
  { name: "Sri Lanka", en: "Sri Lanka", code: "LKA", code2: "lk", continent: "asia", capital: "Sri Jayawardenepura Kotte" },
  { name: "Sudan", en: "Sudan", code: "SDN", code2: "sd", continent: "africa", capital: "Hartum", capitalEn: "Khartoum" },
  { name: "Surinam", en: "Suriname", code: "SUR", code2: "sr", continent: "southAmerica", capital: "Paramaribo" },
  { name: "İsveç", en: "Sweden", code: "SWE", code2: "se", continent: "europe", capital: "Stockholm" },
  { name: "İsviçre", en: "Switzerland", code: "CHE", code2: "ch", continent: "europe", capital: "Bern" },
  { name: "Suriye", en: "Syria", code: "SYR", code2: "sy", continent: "asia", capital: "Şam", capitalEn: "Damascus" },
  { name: "Tayvan", en: "Taiwan", code: "TWN", code2: "tw", continent: "asia", capital: "Taipei" },
  { name: "Tacikistan", en: "Tajikistan", code: "TJK", code2: "tj", continent: "asia", capital: "Duşanbe", capitalEn: "Dushanbe" },
  { name: "Tanzanya", en: "Tanzania", code: "TZA", code2: "tz", continent: "africa", capital: "Dodoma" },
  { name: "Tayland", en: "Thailand", code: "THA", code2: "th", continent: "asia", capital: "Bangkok" },
  { name: "Doğu Timor", en: "Timor-Leste", code: "TLS", code2: "tl", continent: "asia", capital: "Dili" },
  { name: "Togo", en: "Togo", code: "TGO", code2: "tg", continent: "africa", capital: "Lome", capitalEn: "Lomé" },
  { name: "Tonga", en: "Tonga", code: "TON", code2: "to", continent: "oceania", capital: "Nukualofa", capitalEn: "Nukuʻalofa", isSmallIsland: true },
  { name: "Trinidad ve Tobago", en: "Trinidad and Tobago", code: "TTO", code2: "tt", continent: "northAmerica", capital: "Port of Spain", isSmallIsland: true },
  { name: "Tunus", en: "Tunisia", code: "TUN", code2: "tn", continent: "africa", capital: "Tunus", capitalEn: "Tunis" },
  { name: "Türkiye", en: "Turkey", code: "TUR", code2: "tr", continent: "europe", capital: "Ankara" },
  { name: "Türkmenistan", en: "Turkmenistan", code: "TKM", code2: "tm", continent: "asia", capital: "Aşkabat", capitalEn: "Ashgabat" },
  { name: "Uganda", en: "Uganda", code: "UGA", code2: "ug", continent: "africa", capital: "Kampala" },
  { name: "Ukrayna", en: "Ukraine", code: "UKR", code2: "ua", continent: "europe", capital: "Kiev", capitalEn: "Kyiv" },
  { name: "Birleşik Arap Emirlikleri", en: "United Arab Emirates", code: "ARE", code2: "ae", continent: "asia", capital: "Abu Dabi", capitalEn: "Abu Dhabi" },
  { name: "Birleşik Krallık", en: "United Kingdom", code: "GBR", code2: "gb", continent: "europe", capital: "Londra", capitalEn: "London" },
  { name: "Amerika Birleşik Devletleri", en: "United States", code: "USA", code2: "us", continent: "northAmerica", capital: "Washington", capitalEn: "Washington, D.C." },
  { name: "Uruguay", en: "Uruguay", code: "URY", code2: "uy", continent: "southAmerica", capital: "Montevideo" },
  { name: "Özbekistan", en: "Uzbekistan", code: "UZB", code2: "uz", continent: "asia", capital: "Taşkent", capitalEn: "Tashkent" },
  { name: "Vanuatu", en: "Vanuatu", code: "VUT", code2: "vu", continent: "oceania", capital: "Port Vila", isSmallIsland: true },
  { name: "Vatikan", en: "Vatican City", code: "VAT", code2: "va", continent: "europe", capital: "Vatikan", capitalEn: "Vatican City" },
  { name: "Venezuela", en: "Venezuela", code: "VEN", code2: "ve", continent: "southAmerica", capital: "Karakas", capitalEn: "Caracas" },
  { name: "Vietnam", en: "Vietnam", code: "VNM", code2: "vn", continent: "asia", capital: "Hanoi" },
  { name: "Yemen", en: "Yemen", code: "YEM", code2: "ye", continent: "asia", capital: "Sana", capitalEn: "Sanaa" },
  { name: "Zambiya", en: "Zambia", code: "ZMB", code2: "zm", continent: "africa", capital: "Lusaka" },
  { name: "Zimbabve", en: "Zimbabwe", code: "ZWE", code2: "zw", continent: "africa", capital: "Harare" },
  { name: "Batı Sahra", en: "Western Sahara", code: "ESH", code2: "eh", continent: "africa", capital: "Layun", capitalEn: "Laayoune" },
  { name: "Grönland", en: "Greenland", code: "GRL", code2: "gl", continent: "northAmerica", capital: "Nuuk" },
  { name: "Porto Riko", en: "Puerto Rico", code: "PRI", code2: "pr", continent: "northAmerica", capital: "San Juan" },
  { name: "Falkland Adaları", en: "Falkland Islands", code: "FLK", code2: "fk", continent: "southAmerica", capital: "Stanley" },
  { name: "Antarktika", en: "Antarctica", code: "ATA", code2: "aq", continent: "antarctica" },
  { name: "Yeni Kaledonya", en: "New Caledonia", code: "NCL", code2: "nc", continent: "oceania", capital: "Numea", capitalEn: "Nouméa" },
];

// Shuffle an array (Fisher-Yates)
export function shuffleArray<T>(arr: T[]): T[] {
  const result = [...arr];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

// Sub-path the site is served from (see next.config.mjs)
export const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export const flagUrl = (code2: string) => `${BASE}/flags/${code2}.png`;
