// Writes lib/neighbors.ts: countries that share a border in public/countries-50m.json.
// Run with `node scripts/neighbors.ts` after the map file changes.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { numericToAlpha3 } from "../lib/geo.ts";

// topojson-client comes with react-simple-maps, so it is resolved from there
const require = createRequire(createRequire(import.meta.url).resolve("react-simple-maps"));
const { neighbors } = require("topojson-client");

const topo = JSON.parse(readFileSync("public/countries-50m.json", "utf8"));
const geoms = topo.objects.countries.geometries;
// Somaliland and N. Cyprus count as Somalia and Cyprus, so their borders are not lost
const byName: Record<string, string> = { Kosovo: "XKX", Somaliland: "SOM", "N. Cyprus": "CYP" };
const codes = geoms.map((g: any) => byName[g.properties?.name] ?? numericToAlpha3[g.id] ?? null);

const out: Record<string, Set<string>> = {};
neighbors(geoms).forEach((list: number[], i: number) => {
  for (const j of list) {
    const [a, b] = [codes[i], codes[j]];
    if (!a || !b || a === b) continue;
    (out[a] ??= new Set()).add(b);
  }
});

const lines = Object.keys(out)
  .sort()
  .map((code) => `  ${code}: ${JSON.stringify([...out[code]].sort())},`);
writeFileSync(
  "lib/neighbors.ts",
  `// Generated by scripts/neighbors.ts from the map shapes; do not edit by hand.\nexport const neighbors: Record<string, string[]> = {\n${lines.join("\n")}\n};\n`
);
console.log(`${lines.length} countries with neighbours`);
